// Worktree pipeline run model (live, non-persisted). Each selected plan step
// runs in its own git worktree + branch; on completion it's committed and merged
// into a dedicated integration branch, in dependency order. The runner lives in
// useFleet; these are the shapes + the pure builder.
import { Plan } from "../types";
import { ClaudeEffort } from "./plan";

export type WtPhase =
  | "pending" // waiting on deps / a free merge slot
  | "running" // claude working in the step worktree
  | "committing" // staging + commit
  | "merging" // merging into the integration branch
  | "resolving" // claude resolving a merge conflict
  | "done"
  | "error";

export type WtStep = {
  stepId: string;
  title: string;
  prompt: string;
  deps: string[]; // step ids within this run
  branch: string;
  dir: string;
  termId?: string; // session doing the work
  resolveTermId?: string; // session resolving a conflict
  phase: WtPhase;
  note?: string; // short status detail / error
};

/** One timeline entry in a run's activity log. Step-level entries name the step
 *  + its branch; the run-level finish entry uses phase "final" with no stepId. */
export type WtLogEntry = {
  at: number; // epoch ms
  title: string; // step title, or "플랜 완료" / "실행 중지" for run-level
  phase: WtPhase | "final";
  from?: WtPhase; // previous phase (distinguishes clean merge from conflict-resolve)
  stepId?: string;
  branch?: string;
  note?: string; // detail / error message
};

export type WtRun = {
  projectId: string;
  cwd: string; // repo root (normalized to forward slashes)
  branch: string; // integration branch (fleet/plan-XXXX)
  integDir: string; // integration worktree path
  steps: WtStep[];
  auto: boolean; // launch sessions with --dangerously-skip-permissions
  effort?: ClaudeEffort; // reasoning effort for step sessions (--effort)
  log?: WtLogEntry[]; // activity timeline (which branch merged when, conflicts, errors)
  startedAt?: number; // when the run was created (epoch ms)
};

export const PHASE_LABEL: Record<WtPhase, string> = {
  pending: "대기",
  running: "작업 중",
  committing: "커밋 중",
  merging: "병합 중",
  resolving: "충돌 해결 중",
  done: "완료",
  error: "오류",
};

/** Build a fresh run skeleton from a plan + selected step ids. `slug` makes the
 *  branch/dir names unique per run (generated by the caller). */
export function buildWtRun(
  projectId: string,
  cwdRaw: string,
  plan: Plan,
  stepIds: string[],
  auto: boolean,
  slug: string,
  effort?: ClaudeEffort,
): WtRun {
  const cwd = cwdRaw.replace(/\\/g, "/").replace(/\/+$/, "");
  const selSet = new Set(stepIds);
  const sel = plan.steps.filter((s) => selSet.has(s.id));
  const wtRoot = `${cwd}/.fleet/wt`;
  const steps: WtStep[] = sel.map((s, i) => ({
    stepId: s.id,
    title: s.title,
    prompt: s.prompt,
    deps: s.deps.filter((d) => selSet.has(d)),
    branch: `fleet/s-${slug}-${i}`,
    dir: `${wtRoot}/${slug}-${i}`,
    phase: "pending",
  }));
  return {
    projectId,
    cwd,
    branch: `fleet/plan-${slug}`,
    integDir: `${wtRoot}/_integ-${slug}`,
    steps,
    auto,
    effort,
    log: [],
  };
}

export const wtProgress = (run: WtRun) => ({
  total: run.steps.length,
  done: run.steps.filter((s) => s.phase === "done").length,
  active: run.steps.filter((s) => !["pending", "done", "error"].includes(s.phase)).length,
  error: run.steps.filter((s) => s.phase === "error").length,
});
